### ISSUE TITLE
Current Video Bookmarks

### ISSUE THREAD

**Issue by ahmed527** [brianlinUM/youtube-timestamps#1]
Thanks for the great extension. 

I have a suggestion assuming I have a lot of bookmarks, the bookmarks of the current video can be put on the top of the list instead of looking for them manually. This way, it will be a lot easier.

**Comment by brianlinUM** [comment]
Hi Ahmed, that's a good idea! And shouldn't be hard to implement. I will include it in v1.1.0-dev, in preparation for the next release.

**Comment by ahmed527** [comment]
Great!. Thanks.

**Comment by ahmed527** [comment]
Thanks
