### ISSUE TITLE
Adding timestamp 00:00:00

### ISSUE THREAD

**Issue by ahmed527** [brianlinUM/youtube-timestamps#2]
Sometimes when selecting a video from a playlist, for example, it adds the timestamp 00:00:00. So, I have to refresh the page. Please see the image below.

![image](https://user-images.githubusercontent.com/15823914/187042479-596ac02a-3b20-4087-8072-b3354f0d21c4.png)

**Comment by brianlinUM** [comment]
Thanks for letting me know. I wasn't able to reproduce this error on my end. It would be helpful if you could provide some step-by-step instructions (starting from the Youtube home page) on how to encounter this error. Thanks for the help!

**Comment by ahmed527** [comment]
I will try to reproduce the issue and let you know. Closing it for now.
Thanks
