### ISSUE TITLE
Search: Title Only is only partially useful. It should Search within the Title AND within our Notes

### ISSUE THREAD

**Issue by Zacchino** [brianlinUM/youtube-timestamps#3]

**Comment by brianlinUM** [comment]
Hi Zacchino thanks for the suggestion, that is a good idea. I have implemented this in v1.1.0-dev, which will be included in the next release. There will be separate filters for title and label, where both need to pass for the video and label to appear.

**Comment by Zacchino** [comment]
Gosh that's... Wow I'm almost in tears. Spent so much time opening the Addon in "Popup Inspection" Mode, to search within the Inspector itself for Keywords.
_(yeah I know, it's like a mini quest I'm re-living in loop, each time I need to search my Notes themselves... So inconvenient compared to what you're developing! Hence why I'm almost in tears... Thank you so much again: but don't get me wrong: I'm still serious about my last E-Mail)._

>"Where both need to pass for the video and label to appear"

Are you talking about the Indexing Engine behind this improved Search?

**Comment by brianlinUM** [comment]
Yeah, the idea is that if the video filter is "Hello" and the label filter is "World" then the video must contain "Hello" and the video's timestamp must contain "World" for the video timestamp to show up in the filtered list. If one of the filters is not entered, then that filter won't apply.

**Comment by Zacchino** [comment]
Oh I didn’t see that comment to my Github Issue post…

Wow! You’re on fire today! Thank you so much.

I’ll do my best giving back to your Paypal or whatever other means to have
(please let me know).


*​- Zac*
